//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ___VARIABLE_sceneName___PresentationLogic {

    func presentSomething(dataEntity: ___VARIABLE_sceneName___.Something.DataEntity)
}

class ___VARIABLE_sceneName___Presenter {

    weak var viewController: ___VARIABLE_sceneName___DisplayLogic?
    weak var router: ___VARIABLE_sceneName___Router?
}

extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresentationLogic {

    // MARK: Do something
    func presentSomething(dataEntity: ___VARIABLE_sceneName___.Something.DataEntity) {

        let viewModel = ___VARIABLE_sceneName___.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
