//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___RoutingLogic: Router {

//     func routeToSomewhere(dataToPass: Int)
}

class ___VARIABLE_sceneName___Router: Router {

    weak var viewController: ___VARIABLE_sceneName___VC?
    var interactor: ___VARIABLE_sceneName___Interactor?
    var prepareForSegueConfigurations: [String: ((_ segue: UIStoryboardSegue) -> Void)] = [:]
}

extension ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RoutingLogic {

    func performSegue(identifier: String, sender: Any?) {
        viewController?.performSegue(withIdentifier: identifier, sender: sender)
    }

    func prepareForSegueConfiguration(for key: String) -> ((UIStoryboardSegue) -> Void)? {
        return prepareForSegueConfigurations[key]
    }

    func setPrepareForSegueConfiguration(for key: String, configuration: ((UIStoryboardSegue) -> Void)?) {
        prepareForSegueConfigurations[key] = configuration
    }
}
